-- liquibase formatted sql

--changeset shulga:1

CREATE TABLE IF NOT EXISTS category
(
    id       bigint generated by default as identity primary key,
    title       TEXT,
    parent_id     bigint

);

